In [14]:
!pip install mlxtend
import numpy as np
import pandas as pd
import csv
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

dataset =[]
with open('Market_Basket_Optimisation.csv') as file:
    reader = csv.reader(file, delimiter=',')
    for row in reader:
        dataset += [row]

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mlxtend in ./.local/lib/python3.10/site-packages (0.23.0)
Requirement already satisfied: scipy>=1.2.1 in /usr/lib/python3/dist-packages (from mlxtend) (1.8.0)
Requirement already satisfied: pandas>=0.24.2 in ./.local/lib/python3.10/site-packages (from mlxtend) (2.1.3)
Requirement already satisfied: numpy>=1.16.2 in ./.local/lib/python3.10/site-packages (from mlxtend) (1.26.1)
Requirement already satisfied: scikit-learn>=1.0.2 in ./.local/lib/python3.10/site-packages (from mlxtend) (1.3.2)
Requirement already satisfied: joblib>=0.13.2 in ./.local/lib/python3.10/site-packages (from mlxtend) (1.3.2)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/lib/python3/dist-packages (from mlxtend) (3.5.1)
Requirement already satisfied: tzdata>=2022.1 in ./.local/lib/python3.10/site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.local/lib/python3.10/site-packages (from pandas>=0.24.2->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas>=0.24.2->mlxtend) (2022.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.local/lib/python3.10/site-packages (from scikit-learn>=1.0.2->mlxtend) (3.2.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.2->mlxtend) (1.16.0)

In [15]:
dataset[0:10]

[['shrimp',
  'almonds',
  'avocado',
  'vegetables mix',
  'green grapes',
  'whole weat flour',
  'yams',
  'cottage cheese',
  'energy drink',
  'tomato juice',
  'low fat yogurt',
  'green tea',
  'honey',
  'salad',
  'mineral water',
  'salmon',
  'antioxydant juice',
  'frozen smoothie',
  'spinach',
  'olive oil'],
 ['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'],
 ['low fat yogurt'],
 ['whole wheat pasta', 'french fries'],
 ['soup', 'light cream', 'shallot'],
 ['frozen vegetables', 'spaghetti', 'green tea'],
 ['french fries']]

In [16]:
len(dataset)

7501

In [17]:
dataset[1:10]

[['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'],
 ['low fat yogurt'],
 ['whole wheat pasta', 'french fries'],
 ['soup', 'light cream', 'shallot'],
 ['frozen vegetables', 'spaghetti', 'green tea'],
 ['french fries']]

In [18]:
te = TransactionEncoder()
x = te.fit_transform(dataset)
x

array([[False,  True,  True, ...,  True, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False]])

In [19]:

te.columns_

[' asparagus',
 'almonds',
 'antioxydant juice',
 'asparagus',
 'avocado',
 'babies food',
 'bacon',
 'barbecue sauce',
 'black tea',
 'blueberries',
 'body spray',
 'bramble',
 'brownies',
 'bug spray',
 'burger sauce',
 'burgers',
 'butter',
 'cake',
 'candy bars',
 'carrots',
 'cauliflower',
 'cereals',
 'champagne',
 'chicken',
 'chili',
 'chocolate',
 'chocolate bread',
 'chutney',
 'cider',
 'clothes accessories',
 'cookies',
 'cooking oil',
 'corn',
 'cottage cheese',
 'cream',
 'dessert wine',
 'eggplant',
 'eggs',
 'energy bar',
 'energy drink',
 'escalope',
 'extra dark chocolate',
 'flax seed',
 'french fries',
 'french wine',
 'fresh bread',
 'fresh tuna',
 'fromage blanc',
 'frozen smoothie',
 'frozen vegetables',
 'gluten free bar',
 'grated cheese',
 'green beans',
 'green grapes',
 'green tea',
 'ground beef',
 'gums',
 'ham',
 'hand protein bar',
 'herb & pepper',
 'honey',
 'hot dogs',
 'ketchup',
 'light cream',
 'light mayo',
 'low fat yogurt',
 'magazines',
 'mashed potato',
 'mayonnaise',
 'meatballs',
 'melons',
 'milk',
 'mineral water',
 'mint',
 'mint green tea',
 'muffins',
 'mushroom cream sauce',
 'napkins',
 'nonfat milk',
 'oatmeal',
 'oil',
 'olive oil',
 'pancakes',
 'parmesan cheese',
 'pasta',
 'pepper',
 'pet food',
 'pickles',
 'protein bar',
 'red wine',
 'rice',
 'salad',
 'salmon',
 'salt',
 'sandwich',
 'shallot',
 'shampoo',
 'shrimp',
 'soda',
 'soup',
 'spaghetti',
 'sparkling water',
 'spinach',
 'strawberries',
 'strong cheese',
 'tea',
 'tomato juice',
 'tomato sauce',
 'tomatoes',
 'toothpaste',
 'turkey',
 'vegetables mix',
 'water spray',
 'white wine',
 'whole weat flour',
 'whole wheat pasta',
 'whole wheat rice',
 'yams',
 'yogurt cake',
 'zucchini']

In [20]:
df = pd.DataFrame(x, columns=te.columns_)
df

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [21]:
# Frequent items
freq_itemset = apriori(df, min_support=0.01, use_colnames=True)

In [12]:
freq_itemset

      support                                 itemsets
0    0.020397                                (almonds)
1    0.033329                                (avocado)
2    0.010799                         (barbecue sauce)
3    0.014265                              (black tea)
4    0.011465                             (body spray)
..        ...                                      ...
252  0.011065       (milk, mineral water, ground beef)
253  0.017064  (spaghetti, mineral water, ground beef)
254  0.015731         (milk, spaghetti, mineral water)
255  0.010265    (spaghetti, mineral water, olive oil)
256  0.011465     (pancakes, spaghetti, mineral water)

[257 rows x 2 columns]

In [22]:
rules = association_rules(freq_itemset, metric='confidence', min_threshold=0.10)

In [23]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(avocado),(mineral water),0.033329,0.238368,0.011598,0.348000,1.459926,0.003654,1.168147,0.325896
1,(burgers),(cake),0.087188,0.081056,0.011465,0.131498,1.622319,0.004398,1.058080,0.420238
2,(cake),(burgers),0.081056,0.087188,0.011465,0.141447,1.622319,0.004398,1.063198,0.417434
3,(chocolate),(burgers),0.163845,0.087188,0.017064,0.104150,1.194537,0.002779,1.018933,0.194767
4,(burgers),(chocolate),0.087188,0.163845,0.017064,0.195719,1.194537,0.002779,1.039630,0.178411
...,...,...,...,...,...,...,...,...,...,...
315,(olive oil),"(spaghetti, mineral water)",0.065858,0.059725,0.010265,0.155870,2.609786,0.006332,1.113898,0.660314
316,"(pancakes, spaghetti)",(mineral water),0.025197,0.238368,0.011465,0.455026,1.908923,0.005459,1.397557,0.488452
317,"(pancakes, mineral water)",(spaghetti),0.033729,0.174110,0.011465,0.339921,1.952333,0.005593,1.251198,0.504819
318,"(spaghetti, mineral water)",(pancakes),0.059725,0.095054,0.011465,0.191964,2.019529,0.005788,1.119933,0.536902
319,(pancakes),"(spaghetti, mineral water)",0.095054,0.059725,0.011465,0.120617,2.019529,0.005788,1.069244,0.557862

In [24]:
rules=rules[['antecedents','consequents','support','confidence']]

In [25]:
rules

,antecedents,consequents,support,confidence
0,(avocado),(mineral water),0.011598,0.348000
1,(burgers),(cake),0.011465,0.131498
2,(cake),(burgers),0.011465,0.141447
3,(chocolate),(burgers),0.017064,0.104150
4,(burgers),(chocolate),0.017064,0.195719
...,...,...,...,...
315,(olive oil),"(spaghetti, mineral water)",0.010265,0.155870
316,"(pancakes, spaghetti)",(mineral water),0.011465,0.455026
317,"(pancakes, mineral water)",(spaghetti),0.011465,0.339921
318,"(spaghetti, mineral water)",(pancakes),0.011465,0.191964
319,(pancakes),"(spaghetti, mineral water)",0.011465,0.120617

In [33]:
rules[rules['antecedents']=={'cake'}]['consequents']

2               (burgers)
25            (chocolate)
27                 (eggs)
29         (french fries)
30    (frozen vegetables)
33            (green tea)
35                 (milk)
37        (mineral water)
39             (pancakes)
41            (spaghetti)
Name: consequents, dtype: object